import { Event, EventCategory } from "../types";

export const eventsMock: Event[] = [
  {
    id: 'a9dc53a5-2b13-43d4-a149-5fb24d7da488',
    title: 'Event 1 - Meeting Expert',
    category: EventCategory.MEETING_EXPERT,
    startDate: '11/30/2024',
    startTime: '19:00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus maximus scelerisque magna nec tincidunt. Sed a volutpat ex. Nam euismod tempor velit id laoreet. Aliquam varius ex eu nulla finibus, ut rutrum libero fringilla.',
    location: 'Stereo Plaza, Kyiv, Ukraine',
  },
  {
    id: 'fd96d818-3d89-497b-b64f-d4537b5f53dc',
    title: 'Event 2',
    category: EventCategory.WEBINAR,
    startDate: '11/30/2024',
    startTime: '13:00',
    description: 'Aliquam eget placerat est. Suspendisse pulvinar cursus magna, vitae pellentesque sapien faucibus ac. Fusce et dapibus nisl, in consectetur lorem. Aenean imperdiet dictum pellentesque. Curabitur ullamcorper purus eget accumsan lobortis.',
    location: 'Stereo Plaza, Kyiv, Ukraine',
  },
  {
    id: 'gp21a818-3d89-326o-b64f-d4537b1a33en',
    title: 'Event 3',
    category: EventCategory.CONFERENCE,
    startDate: '12/1/2024',
    startTime: '16:00',
    description: 'Aliquam eget placerat est. Suspendisse pulvinar cursus magna, vitae pellentesque sapien faucibus ac. Fusce et dapibus nisl, in consectetur lorem. Aenean imperdiet dictum pellentesque. Curabitur ullamcorper purus eget accumsan lobortis.',
    location: 'Stereo Plaza, Kyiv, Ukraine',
  },
  {
    id: '8ece22dc-6568-429e-b36f-ccb2da109f51',
    title: 'Event 4',
    category: EventCategory.MEETING_EXPERT,
    startDate: '12/18/2024',
    startTime: '17:00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus maximus scelerisque magna nec tincidunt. Sed a volutpat ex. Nam euismod tempor velit id laoreet. Aliquam varius ex eu nulla finibus, ut rutrum libero fringilla.',
    location: 'Stereo Plaza, Kyiv, Ukraine',
  },
  {
    id: 'd8ae53c0-fb1d-42e6-baa0-df3d26e4d22a',
    title: 'Event 5',
    category: EventCategory.SESSION_QA,
    startDate: '12/18/2024',
    startTime: '19:00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus maximus scelerisque magna nec tincidunt. Sed a volutpat ex. Nam euismod tempor velit id laoreet. Aliquam varius ex eu nulla finibus, ut rutrum libero fringilla.',
    location: 'Stereo Plaza, Kyiv, Ukraine',
  },
  {
    id: '6ab46ed9-9ace-4c9c-bbf9-ad8b575ff70d',
    title: 'Event 6',
    category: EventCategory.CONFERENCE,
    startDate: '12/18/2024',
    startTime: '17:00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus maximus scelerisque magna nec tincidunt. Sed a volutpat ex. Nam euismod tempor velit id laoreet. Aliquam varius ex eu nulla finibus, ut rutrum libero fringilla.',
    location: 'Stereo Plaza, Kyiv, Ukraine',
  },
  {
    id: 'ecb59e7d-bdf4-4dad-a051-e5773289b859',
    title: 'Event 7',
    category: EventCategory.WEBINAR,
    startDate: '12/21/2024',
    startTime: '17:00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus maximus scelerisque magna nec tincidunt. Sed a volutpat ex. Nam euismod tempor velit id laoreet. Aliquam varius ex eu nulla finibus, ut rutrum libero fringilla.',
    location: 'Stereo Plaza, Kyiv, Ukraine',
  },
  {
    id: 'f3e8d914-3af7-49c0-ab02-aa5a812ceb9e',
    title: 'Event 8',
    category: EventCategory.MEETING_EXPERT,
    startDate: '12/22/2024',
    startTime: '12:00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus maximus scelerisque magna nec tincidunt. Sed a volutpat ex. Nam euismod tempor velit id laoreet. Aliquam varius ex eu nulla finibus, ut rutrum libero fringilla.',
    location: 'Stereo Plaza, Kyiv, Ukraine',
  },
  {
    id: 'a1f596ac-db4a-4a27-84db-2c5daecdb9d0',
    title: 'New Year',
    category: EventCategory.CONFERENCE,
    startDate: '12/31/2024',
    startTime: '23:59',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus maximus scelerisque magna nec tincidunt. Sed a volutpat ex. Nam euismod tempor velit id laoreet. Aliquam varius ex eu nulla finibus, ut rutrum libero fringilla.',
    location: 'Stereo Plaza, Kyiv, Ukraine',
  },
  {
    id: '9c137e5b-4e55-4e1d-9028-e7b79bcadd34',
    title: 'Event 9',
    category: EventCategory.SESSION_QA,
    startDate: '1/1/2025',
    startTime: '17:00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus maximus scelerisque magna nec tincidunt. Sed a volutpat ex. Nam euismod tempor velit id laoreet. Aliquam varius ex eu nulla finibus, ut rutrum libero fringilla.',
    location: 'Stereo Plaza, Kyiv, Ukraine',
  },
  {
    id: 'a24baa61-2306-4939-a0f3-78f07333ee65',
    title: 'Event 10',
    category: EventCategory.MEETING_EXPERT,
    startDate: '1/5/2025',
    startTime: '13:00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus maximus scelerisque magna nec tincidunt. Sed a volutpat ex. Nam euismod tempor velit id laoreet. Aliquam varius ex eu nulla finibus, ut rutrum libero fringilla.',
    location: 'Stereo Plaza, Kyiv, Ukraine',
  },
  {
    id: '4af5d1b3-dc53-4e00-8dd3-886aca2e5d4a',
    title: 'Event 11',
    category: EventCategory.SESSION_QA,
    startDate: '1/25/2025',
    startTime: '17:00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus maximus scelerisque magna nec tincidunt. Sed a volutpat ex. Nam euismod tempor velit id laoreet. Aliquam varius ex eu nulla finibus, ut rutrum libero fringilla.',
    location: 'Stereo Plaza, Kyiv, Ukraine',
  },
  {
    id: '7efde3e8-3705-4ddb-ba8b-7c87ea6c3089',
    title: 'Event 12',
    category: EventCategory.CONFERENCE,
    startDate: '2/10/2025',
    startTime: '17:00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus maximus scelerisque magna nec tincidunt. Sed a volutpat ex. Nam euismod tempor velit id laoreet. Aliquam varius ex eu nulla finibus, ut rutrum libero fringilla.',
    location: 'Stereo Plaza, Kyiv, Ukraine',
  },
  {
    id: '7cb11138-023f-4821-ba28-c760c2d54de2',
    title: 'Event 13',
    category: EventCategory.SESSION_QA,
    startDate: '2/27/2025',
    startTime: '17:00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus maximus scelerisque magna nec tincidunt. Sed a volutpat ex. Nam euismod tempor velit id laoreet. Aliquam varius ex eu nulla finibus, ut rutrum libero fringilla.',
    location: 'Stereo Plaza, Kyiv, Ukraine',
  },
  {
    id: 'dc38a090-dde9-4a99-9feb-7fd7b2f83d54',
    title: 'Event 14',
    category: EventCategory.MEETING_EXPERT,
    startDate: '4/19/2025',
    startTime: '17:00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus maximus scelerisque magna nec tincidunt. Sed a volutpat ex. Nam euismod tempor velit id laoreet. Aliquam varius ex eu nulla finibus, ut rutrum libero fringilla.',
    location: 'Stereo Plaza, Kyiv, Ukraine',
  },
];